# Generated by Django 5.1.3 on 2024-11-21 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='registered_hackathons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requesttobeorganizer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
