# Generated by Django 5.1.3 on 2024-11-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hackathon_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hackathon_covers/'),
        ),
    ]
