# Generated by Django 5.1.3 on 2024-11-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hackathon_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
